#!/bin/bash

source "$HOME/.config/user-dirs.dirs"

#it's important
IFS='
'

generateDesktopEntry() {
	EXEC=$1
	DESK_TEXT="
[Desktop Entry]
Version=1.0
Type=Application
Encoding=UTF-8
Name=$NAME_WITHOUT_EXT
Exec=$EXEC
Path=$MYDIR
StartupWMClass=$BASENAME"
}


EXECUTABLE=false
checkExecutable(){
	if [ ! -z "`file $1 | grep 'executable'`" ]; then
		EXECUTABLE=true
	else
		EXECUTABLE=false
	fi
}


ICON_FORMAT_LIST="ico png gif tif jpg jpeg bmp"
ICON=false
checkIcon(){
	if [ ! -z "`echo "$ICON_FORMAT_LIST" | grep $1`" ]; then
		ICON=true
	else
		ICON=false
	fi
}


EXECUTABLE_FOUND=false
DONE=false

for FILE in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do
	MYDIR=`dirname $FILE`
	BASENAME=`basename $FILE`
	EXT=$(echo $BASENAME | cut -f 2 -d '.')
	NAME_WITHOUT_EXT=$(echo $BASENAME | cut -f 1 -d '.')

	DESKTOP_FILE=$XDG_DESKTOP_DIR/$BASENAME.desktop

	generateDesktopEntry "bash -c './$BASENAME'"

	checkExecutable $FILE
	checkIcon $EXT

	echo "EXECUTABLE $EXECUTABLE"
	echo "EXECUTABLE_FOUND $EXECUTABLE_FOUND"
	echo "$EXT"

	#first executable found and windows .exe
	if [ "$EXECUTABLE" == true ] && [ "$EXECUTABLE_FOUND" == false ] && [ "$EXT" == "exe" ]; then
		generateDesktopEntry "wine start.exe /Unix ./'$BASENAME'"

		#extract icon if not selected
		if  [ -z $DESK_ICON ]; then
			ICONSDIR=$XDG_DESKTOP_DIR/.exeicons
			mkdir $XDG_DESKTOP_DIR/.exeicons

			#extract .ico
			wrestool -t 'group_icon' -o $ICONSDIR/$BASENAME.ico -x $FILE
			#convert to png
			icotool -x -o $ICONSDIR/$BASENAME.png $ICONSDIR/$BASENAME.ico

			DESK_ICON="$ICONSDIR/$BASENAME.png"
		fi
	elif [ "$ICON" == true ]; then
		DESK_ICON=$FILE
	fi

	if [ "$EXECUTABLE" == true ]; then
		EXECUTABLE_FOUND=true
	fi

	if [ "$EXECUTABLE_FOUND" == true ] && [ ! -z $DESK_ICON ]; then
		break
	fi
done


DESK_TEXT="$DESK_TEXT
Icon=$DESK_ICON"

echo "$DESK_TEXT" > $DESKTOP_FILE
chmod +x $DESKTOP_FILE
